'📚 Documentation':
  - '(doc|markdown|readme)'
'🔧 Fix':
  - '(fix)'
'🌟 New Feature':
  - '(ft|feat|implement|create)'
'🔄 Refactor':
  - '(refactor|update|change|optimize|improve|remove)'
'🎨 SCSS':
  - '(scss|css|style|theme)'