[build]
  args_bin = ["-checkupdate=false"]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 0
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  include_ext = ["go", "html", "scss"]
  kill_delay = "0s"
  log = "build-errors.log"
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true