name: Label Issues and Pull Requests
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.2
        with:
          configuration-path: '.github/labeler.yml'
          include-title: 1
          include-body: 0
          sync-labels: 1
          repo-token: ${{ github.token }}