name: Label Pull Requests
on:
  pull_request:
    types: [opened, edited]

permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.2
        with:
          configuration-path: '.github/pr_labeler.yml'
          include-title: 1
          include-body: 0
          enable-versioned-regex: 0
          sync-labels: 1
          repo-token: ${{ github.token }}