name: Draft Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  draftrelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: 'release_drafter.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}